FROM ubuntu:20.04

WORKDIR /usr/src/app/mbed-edge-examples

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata && \
    apt-get install -y build-essential \
    git \
    libc6-dev \
    cmake \
    python3.6 python3-pip python3-setuptools python3-venv

COPY . .

RUN rm -rf build build-debug
RUN make build-pt-example-debug

CMD [ "./build-debug/bin/pt-example", "-n", "docker-pt-example" ]