name: mbed-edge-examples-make

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/README.md'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  

jobs:
  make-examples:
    runs-on: edge-example-ci
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
    - name: Checkout continuous-integration
      uses: actions/checkout@v4
      # Self hosted has dependencies in place already
      # - name: Install dependencies
      # run: |
        # sudo apt install build-essential git libc6-dev
        # sudo apt install libmosquitto-dev mosquitto-clients
        # sudo apt install libglib2.0-dev
        # sudo apt install doxygen
    - name: git submodule update
      run: git submodule update --init --recursive
    # This builds release, debug and sanitize versions.
    - run: make all

  docker-build:
    runs-on: edge-example-ci
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout continuous-integration
        uses: actions/checkout@v4
      - name: git submodule update
        run: git submodule update --init --recursive
      - name: Docker build
        run: docker build -t pt-example:latest -f ./Dockerfile.pt-example .
        # Don't run it - it will run forever essentially.
