name: misspell
on: 
  push:
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: mbed-edge-misspell-'${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  static-checks:
    runs-on: client
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Misspell
        uses: PelionIoT/actions/.github/actions/misspell@main
        with:
          exceptions: "mosquitto"
          path: ".github blept-example byte-order \
                     c-api-stress-tester cmake config device-interface examples-common \
                     examples-common-2 include mqttpt-example pt-example \
                     simple-js-examples/*.js simple-js-examples/*.md \
                     CHANGELOG.md CMakeLists.txt CONTRIBUTING.md Do* Makefile README.md"
